### ISSUE TITLE
Very slow when in ListView

### ISSUE THREAD

**Issue by prasadsunny1** [Solido/Flutter-BlurHash#1]
The screen is freezing.
Here is what I did

`import 'package:flutter/material.dart';
import 'package:flutter_blurhash/flutter_blurhash.dart';

class BlurHashPage extends StatelessWidget {
  var hashList = [
    "L5H2EC=PM+yV0g-mq.wG9c010J}I",
    'LEHV6nWB2yk8pyo0adR*.7kCMdnj',
    "BkF=hb}MQ+=S#lNL",
    "B6C=+r000000?d9p",
    "BWJaZl^:^ky__\$jb",
    "BEM3Hy?K0x,.wgI=",
    "BWFpeiEb=RNx;EW?",
  ];
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text("Blur Hash"),
      ),
      body: ListView.builder(
        itemCount: hashList.length,
        itemBuilder: (context, index) {
          return Card(
            clipBehavior: Clip.hardEdge,
            shape: RoundedRectangleBorder(
              borderRadius: BorderRadius.circular(10.0),
            ),
            child: SizedBox(
              height: 200,
              child: BlurHash(
                hash: hashList[index],
                color: Colors.lightBlue,
              ),
            ),
          );
        },
      ),
    );
  }
}
`

**Comment by cbenhagen** [comment]
#2 will fix this ;)

@prasadsunny1 you can make your github code snippets much prettier by using [code blocks](https://help.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks).

**Comment by prasadsunny1** [comment]
Thanks for the solution and tip
